# Generated by Django 3.2.6 on 2021-09-26 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_rating',
            name='product_id',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='product_rating',
            name='rating',
            field=models.IntegerField(blank=True),
        ),
    ]
