# Generated by Django 3.2.6 on 2021-10-12 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210926_1541'),
    ]

    operations = [
        migrations.CreateModel(
            name='sale_notification',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('user_email', models.CharField(blank=True, max_length=100)),
                ('brand_name', models.CharField(blank=True, max_length=100)),
                ('subscribe', models.BooleanField(blank=True)),
            ],
            options={
                'db_table': 'sale_notification',
            },
        ),
    ]
