# Generated by Django 3.2.6 on 2021-10-17 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20211015_0019'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='overview',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
