# Generated by Django 3.2.6 on 2021-10-21 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_bookmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='brand_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
