# Generated by Django 3.2.6 on 2021-10-21 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_bookmark_brand_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='recommended_item',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('product_id', models.IntegerField(blank=True, null=True)),
                ('brand_name', models.CharField(blank=True, max_length=100)),
                ('username', models.CharField(blank=True, max_length=50)),
                ('title', models.CharField(blank=True, max_length=50)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('sale_price', models.IntegerField(blank=True, null=True)),
                ('product_link', models.URLField(blank=True)),
                ('image_link', models.URLField(blank=True)),
                ('image_link2', models.URLField(blank=True)),
                ('rating', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'recommended_item',
            },
        ),
    ]
