# Generated by Django 3.2.6 on 2021-10-22 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_recommended_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommended_item',
            name='overview',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
