# Generated by Django 3.2.6 on 2021-10-22 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_recommended_item_overview'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommended_item',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.brands'),
        ),
        migrations.AddField(
            model_name='recommended_item',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product_type'),
        ),
        migrations.AddField(
            model_name='recommended_item',
            name='category_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='recommended_item',
            name='datee',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='recommended_item',
            name='detail',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='recommended_item',
            name='gender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.gender'),
        ),
        migrations.AddField(
            model_name='recommended_item',
            name='gender_category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='recommended_item',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
