# Generated by Django 3.2.6 on 2021-11-09 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20211109_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='image_link',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='image_link2',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_link',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_link2',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='recommended_item',
            name='image_link',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='recommended_item',
            name='image_link2',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='recommended_item',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_rating',
            name='image_link',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='user_rating',
            name='image_link2',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
